Repository netlify/node-template, pull requests merged in 2021-02, with the labels that each got.

#21 chore: support Node 15
  {{cookiecutter.project_slug}}/.github/workflows/workflow.yml
Labels: type: chore

#22 chore: fix linting and formatting on npm@7
  {{cookiecutter.project_slug}}/package.json
Labels: type: chore

#23 feat: add husky to dev dependencies
  {{cookiecutter.project_slug}}/package.json
Labels: type: feature

#24 fix: fix `files` in `package.json`
  {{cookiecutter.project_slug}}/package.json
Labels: type: bug
