Repository netlify/node-template, pull requests merged in 2021-01, with the labels that each got.

#15 chore: limit renovate updates to template dependencies
  renovate.json5
Labels: type: chore

#17 chore: don't renovate lockfile
  renovate.json5
  {{cookiecutter.project_slug}}/package-lock.json
Labels: type: chore

#16 fix: update initial commit message
  hooks/post_gen_project.py
Labels: type: bug

#18 Add `CODEOWNERS`
  .github/CODEOWNERS
Labels: type: chore

#19 feature: add prepublish script
  {{cookiecutter.project_slug}}/package.json
Labels: type: feature

#20 fix: update PR labeler to use a matrix
  {{cookiecutter.project_slug}}/.github/workflows/labeler.yml
Labels: type: bug
