Repository netlify/node-template, pull requests merged in 2022-01, with the labels that each got.

#109 chore: add Kodiak
  .github/.kodiak.toml
Labels: type: chore

#115 chore: fix Husky
  {{cookiecutter.project_slug}}/package-lock.json
  {{cookiecutter.project_slug}}/package.json
Labels: type: chore, automerge

#116 fix: husky binary not found
  {{cookiecutter.project_slug}}/package-lock.json
  {{cookiecutter.project_slug}}/package.json
Labels: type: bug, automerge

#118 chore(docs-pr-template): add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: chore, automerge

#93 feat: Migrate to TypeScript
  {{cookiecutter.project_slug}}/.gitignore
  {{cookiecutter.project_slug}}/package-lock.json
  {{cookiecutter.project_slug}}/package.json
  {{cookiecutter.project_slug}}/src/main.js
  {{cookiecutter.project_slug}}/src/main.ts
  {{cookiecutter.project_slug}}/tsconfig.json
Labels: type: feature, automerge
